/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.0)", date = "2019-11-06")
public class BuddyOnAirUrls implements org.apache.thrift.TBase<BuddyOnAirUrls, BuddyOnAirUrls._Fields>, java.io.Serializable, Cloneable, Comparable<BuddyOnAirUrls> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("BuddyOnAirUrls");

  private static final org.apache.thrift.protocol.TField HLS_FIELD_DESC = new org.apache.thrift.protocol.TField("hls", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField SMOOTH_STREAMING_FIELD_DESC = new org.apache.thrift.protocol.TField("smoothStreaming", org.apache.thrift.protocol.TType.MAP, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new BuddyOnAirUrlsStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new BuddyOnAirUrlsTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> hls; // required
  public @org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> smoothStreaming; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HLS((short)1, "hls"),
    SMOOTH_STREAMING((short)2, "smoothStreaming");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HLS
          return HLS;
        case 2: // SMOOTH_STREAMING
          return SMOOTH_STREAMING;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HLS, new org.apache.thrift.meta_data.FieldMetaData("hls", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.SMOOTH_STREAMING, new org.apache.thrift.meta_data.FieldMetaData("smoothStreaming", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(BuddyOnAirUrls.class, metaDataMap);
  }

  public BuddyOnAirUrls() {
  }

  public BuddyOnAirUrls(
    java.util.Map<java.lang.String,java.lang.String> hls,
    java.util.Map<java.lang.String,java.lang.String> smoothStreaming)
  {
    this();
    this.hls = hls;
    this.smoothStreaming = smoothStreaming;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public BuddyOnAirUrls(BuddyOnAirUrls other) {
    if (other.isSetHls()) {
      java.util.Map<java.lang.String,java.lang.String> __this__hls = new java.util.HashMap<java.lang.String,java.lang.String>(other.hls);
      this.hls = __this__hls;
    }
    if (other.isSetSmoothStreaming()) {
      java.util.Map<java.lang.String,java.lang.String> __this__smoothStreaming = new java.util.HashMap<java.lang.String,java.lang.String>(other.smoothStreaming);
      this.smoothStreaming = __this__smoothStreaming;
    }
  }

  public BuddyOnAirUrls deepCopy() {
    return new BuddyOnAirUrls(this);
  }

  @Override
  public void clear() {
    this.hls = null;
    this.smoothStreaming = null;
  }

  public int getHlsSize() {
    return (this.hls == null) ? 0 : this.hls.size();
  }

  public void putToHls(java.lang.String key, java.lang.String val) {
    if (this.hls == null) {
      this.hls = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.hls.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.String> getHls() {
    return this.hls;
  }

  public BuddyOnAirUrls setHls(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> hls) {
    this.hls = hls;
    return this;
  }

  public void unsetHls() {
    this.hls = null;
  }

  /** Returns true if field hls is set (has been assigned a value) and false otherwise */
  public boolean isSetHls() {
    return this.hls != null;
  }

  public void setHlsIsSet(boolean value) {
    if (!value) {
      this.hls = null;
    }
  }

  public int getSmoothStreamingSize() {
    return (this.smoothStreaming == null) ? 0 : this.smoothStreaming.size();
  }

  public void putToSmoothStreaming(java.lang.String key, java.lang.String val) {
    if (this.smoothStreaming == null) {
      this.smoothStreaming = new java.util.HashMap<java.lang.String,java.lang.String>();
    }
    this.smoothStreaming.put(key, val);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Map<java.lang.String,java.lang.String> getSmoothStreaming() {
    return this.smoothStreaming;
  }

  public BuddyOnAirUrls setSmoothStreaming(@org.apache.thrift.annotation.Nullable java.util.Map<java.lang.String,java.lang.String> smoothStreaming) {
    this.smoothStreaming = smoothStreaming;
    return this;
  }

  public void unsetSmoothStreaming() {
    this.smoothStreaming = null;
  }

  /** Returns true if field smoothStreaming is set (has been assigned a value) and false otherwise */
  public boolean isSetSmoothStreaming() {
    return this.smoothStreaming != null;
  }

  public void setSmoothStreamingIsSet(boolean value) {
    if (!value) {
      this.smoothStreaming = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case HLS:
      if (value == null) {
        unsetHls();
      } else {
        setHls((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    case SMOOTH_STREAMING:
      if (value == null) {
        unsetSmoothStreaming();
      } else {
        setSmoothStreaming((java.util.Map<java.lang.String,java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case HLS:
      return getHls();

    case SMOOTH_STREAMING:
      return getSmoothStreaming();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case HLS:
      return isSetHls();
    case SMOOTH_STREAMING:
      return isSetSmoothStreaming();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof BuddyOnAirUrls)
      return this.equals((BuddyOnAirUrls)that);
    return false;
  }

  public boolean equals(BuddyOnAirUrls that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_hls = true && this.isSetHls();
    boolean that_present_hls = true && that.isSetHls();
    if (this_present_hls || that_present_hls) {
      if (!(this_present_hls && that_present_hls))
        return false;
      if (!this.hls.equals(that.hls))
        return false;
    }

    boolean this_present_smoothStreaming = true && this.isSetSmoothStreaming();
    boolean that_present_smoothStreaming = true && that.isSetSmoothStreaming();
    if (this_present_smoothStreaming || that_present_smoothStreaming) {
      if (!(this_present_smoothStreaming && that_present_smoothStreaming))
        return false;
      if (!this.smoothStreaming.equals(that.smoothStreaming))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetHls()) ? 131071 : 524287);
    if (isSetHls())
      hashCode = hashCode * 8191 + hls.hashCode();

    hashCode = hashCode * 8191 + ((isSetSmoothStreaming()) ? 131071 : 524287);
    if (isSetSmoothStreaming())
      hashCode = hashCode * 8191 + smoothStreaming.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(BuddyOnAirUrls other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetHls()).compareTo(other.isSetHls());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHls()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.hls, other.hls);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetSmoothStreaming()).compareTo(other.isSetSmoothStreaming());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSmoothStreaming()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.smoothStreaming, other.smoothStreaming);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("BuddyOnAirUrls(");
    boolean first = true;

    sb.append("hls:");
    if (this.hls == null) {
      sb.append("null");
    } else {
      sb.append(this.hls);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("smoothStreaming:");
    if (this.smoothStreaming == null) {
      sb.append("null");
    } else {
      sb.append(this.smoothStreaming);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class BuddyOnAirUrlsStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BuddyOnAirUrlsStandardScheme getScheme() {
      return new BuddyOnAirUrlsStandardScheme();
    }
  }

  private static class BuddyOnAirUrlsStandardScheme extends org.apache.thrift.scheme.StandardScheme<BuddyOnAirUrls> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, BuddyOnAirUrls struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HLS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map50 = iprot.readMapBegin();
                struct.hls = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map50.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key51;
                @org.apache.thrift.annotation.Nullable java.lang.String _val52;
                for (int _i53 = 0; _i53 < _map50.size; ++_i53)
                {
                  _key51 = iprot.readString();
                  _val52 = iprot.readString();
                  struct.hls.put(_key51, _val52);
                }
                iprot.readMapEnd();
              }
              struct.setHlsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SMOOTH_STREAMING
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map54 = iprot.readMapBegin();
                struct.smoothStreaming = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map54.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _key55;
                @org.apache.thrift.annotation.Nullable java.lang.String _val56;
                for (int _i57 = 0; _i57 < _map54.size; ++_i57)
                {
                  _key55 = iprot.readString();
                  _val56 = iprot.readString();
                  struct.smoothStreaming.put(_key55, _val56);
                }
                iprot.readMapEnd();
              }
              struct.setSmoothStreamingIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, BuddyOnAirUrls struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.hls != null) {
        oprot.writeFieldBegin(HLS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.hls.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter58 : struct.hls.entrySet())
          {
            oprot.writeString(_iter58.getKey());
            oprot.writeString(_iter58.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.smoothStreaming != null) {
        oprot.writeFieldBegin(SMOOTH_STREAMING_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, struct.smoothStreaming.size()));
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter59 : struct.smoothStreaming.entrySet())
          {
            oprot.writeString(_iter59.getKey());
            oprot.writeString(_iter59.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class BuddyOnAirUrlsTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public BuddyOnAirUrlsTupleScheme getScheme() {
      return new BuddyOnAirUrlsTupleScheme();
    }
  }

  private static class BuddyOnAirUrlsTupleScheme extends org.apache.thrift.scheme.TupleScheme<BuddyOnAirUrls> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, BuddyOnAirUrls struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetHls()) {
        optionals.set(0);
      }
      if (struct.isSetSmoothStreaming()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetHls()) {
        {
          oprot.writeI32(struct.hls.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter60 : struct.hls.entrySet())
          {
            oprot.writeString(_iter60.getKey());
            oprot.writeString(_iter60.getValue());
          }
        }
      }
      if (struct.isSetSmoothStreaming()) {
        {
          oprot.writeI32(struct.smoothStreaming.size());
          for (java.util.Map.Entry<java.lang.String, java.lang.String> _iter61 : struct.smoothStreaming.entrySet())
          {
            oprot.writeString(_iter61.getKey());
            oprot.writeString(_iter61.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, BuddyOnAirUrls struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TMap _map62 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.hls = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map62.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key63;
          @org.apache.thrift.annotation.Nullable java.lang.String _val64;
          for (int _i65 = 0; _i65 < _map62.size; ++_i65)
          {
            _key63 = iprot.readString();
            _val64 = iprot.readString();
            struct.hls.put(_key63, _val64);
          }
        }
        struct.setHlsIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map66 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRING, iprot.readI32());
          struct.smoothStreaming = new java.util.HashMap<java.lang.String,java.lang.String>(2*_map66.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _key67;
          @org.apache.thrift.annotation.Nullable java.lang.String _val68;
          for (int _i69 = 0; _i69 < _map66.size; ++_i69)
          {
            _key67 = iprot.readString();
            _val68 = iprot.readString();
            struct.smoothStreaming.put(_key67, _val68);
          }
        }
        struct.setSmoothStreamingIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

