/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.0)", date = "2019-11-06")
public enum BuddyResultState implements org.apache.thrift.TEnum {
  ACCEPTED(1),
  SUCCEEDED(2),
  FAILED(3),
  CANCELLED(4),
  NOTIFY_FAILED(5),
  STORING(11),
  UPLOADING(21),
  NOTIFYING(31);

  private final int value;

  private BuddyResultState(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static BuddyResultState findByValue(int value) { 
    switch (value) {
      case 1:
        return ACCEPTED;
      case 2:
        return SUCCEEDED;
      case 3:
        return FAILED;
      case 4:
        return CANCELLED;
      case 5:
        return NOTIFY_FAILED;
      case 11:
        return STORING;
      case 21:
        return UPLOADING;
      case 31:
        return NOTIFYING;
      default:
        return null;
    }
  }
}
