/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.0)", date = "2019-11-06")
public enum ContactType implements org.apache.thrift.TEnum {
  MID(0),
  PHONE(1),
  EMAIL(2),
  USERID(3),
  PROXIMITY(4),
  GROUP(5),
  USER(6),
  QRCODE(7),
  PROMOTION_BOT(8),
  REPAIR(128),
  FACEBOOK(2305),
  SINA(2306),
  RENREN(2307),
  FEIXIN(2308);

  private final int value;

  private ContactType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ContactType findByValue(int value) { 
    switch (value) {
      case 0:
        return MID;
      case 1:
        return PHONE;
      case 2:
        return EMAIL;
      case 3:
        return USERID;
      case 4:
        return PROXIMITY;
      case 5:
        return GROUP;
      case 6:
        return USER;
      case 7:
        return QRCODE;
      case 8:
        return PROMOTION_BOT;
      case 128:
        return REPAIR;
      case 2305:
        return FACEBOOK;
      case 2306:
        return SINA;
      case 2307:
        return RENREN;
      case 2308:
        return FEIXIN;
      default:
        return null;
    }
  }
}
