/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.0)", date = "2019-11-06")
public enum IdentityProvider implements org.apache.thrift.TEnum {
  UNKNOWN(0),
  LINE(1),
  NAVER_KR(2);

  private final int value;

  private IdentityProvider(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static IdentityProvider findByValue(int value) { 
    switch (value) {
      case 0:
        return UNKNOWN;
      case 1:
        return LINE;
      case 2:
        return NAVER_KR;
      default:
        return null;
    }
  }
}
