/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
public class NotificationStatus implements org.apache.thrift.TEnum {

  public static final NotificationStatus NOTIFICATION_ITEM_EXIST = new NotificationStatus(1);
  public static final NotificationStatus TIMELINE_ITEM_EXIST = new NotificationStatus(2);
  public static final NotificationStatus NOTE_GROUP_NEW_ITEM_EXIST = new NotificationStatus(4);
  public static final NotificationStatus TIMELINE_BUDDYGROUP_CHANGED = new NotificationStatus(8);
  public static final NotificationStatus NOTE_ONE_TO_ONE_NEW_ITEM_EXIST = new NotificationStatus(16);
  public static final NotificationStatus ALBUM_ITEM_EXIST = new NotificationStatus(32);
  public static final NotificationStatus TIMELINE_ITEM_DELETED = new NotificationStatus(64);

  private final int value;

  private NotificationStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static NotificationStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return NOTIFICATION_ITEM_EXIST;
      case 2:
        return TIMELINE_ITEM_EXIST;
      case 4:
        return NOTE_GROUP_NEW_ITEM_EXIST;
      case 8:
        return TIMELINE_BUDDYGROUP_CHANGED;
      case 16:
        return NOTE_ONE_TO_ONE_NEW_ITEM_EXIST;
      case 32:
        return ALBUM_ITEM_EXIST;
      case 64:
        return TIMELINE_ITEM_DELETED;
      default:
        return null;
    }
  }
}
