/**
 * Autogenerated by Thrift Compiler (0.14.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
public class SettingsAttribute implements org.apache.thrift.TEnum {

  public static final SettingsAttribute NOTIFICATION_ENABLE = new SettingsAttribute(1);
  public static final SettingsAttribute NOTIFICATION_MUTE_EXPIRATION = new SettingsAttribute(2);
  public static final SettingsAttribute NOTIFICATION_NEW_MESSAGE = new SettingsAttribute(4);
  public static final SettingsAttribute NOTIFICATION_GROUP_INVITATION = new SettingsAttribute(8);
  public static final SettingsAttribute NOTIFICATION_SHOW_MESSAGE = new SettingsAttribute(16);
  public static final SettingsAttribute NOTIFICATION_INCOMING_CALL = new SettingsAttribute(32);
  public static final SettingsAttribute PRIVACY_SYNC_CONTACTS = new SettingsAttribute(64);
  public static final SettingsAttribute PRIVACY_SEARCH_BY_PHONE_NUMBER = new SettingsAttribute(128);
  public static final SettingsAttribute NOTIFICATION_SOUND_MESSAGE = new SettingsAttribute(256);
  public static final SettingsAttribute NOTIFICATION_SOUND_GROUP = new SettingsAttribute(512);
  public static final SettingsAttribute CONTACT_MY_TICKET = new SettingsAttribute(1024);
  public static final SettingsAttribute IDENTITY_PROVIDER = new SettingsAttribute(2048);
  public static final SettingsAttribute IDENTITY_IDENTIFIER = new SettingsAttribute(4096);
  public static final SettingsAttribute PRIVACY_SEARCH_BY_USERID = new SettingsAttribute(8192);
  public static final SettingsAttribute PRIVACY_SEARCH_BY_EMAIL = new SettingsAttribute(16384);
  public static final SettingsAttribute PREFERENCE_LOCALE = new SettingsAttribute(32768);
  public static final SettingsAttribute NOTIFICATION_DISABLED_WITH_SUB = new SettingsAttribute(65536);
  public static final SettingsAttribute SNS_ACCOUNT = new SettingsAttribute(524288);
  public static final SettingsAttribute PHONE_REGISTRATION = new SettingsAttribute(1048576);
  public static final SettingsAttribute PRIVACY_ALLOW_SECONDARY_DEVICE_LOGIN = new SettingsAttribute(2097152);
  public static final SettingsAttribute CUSTOM_MODE = new SettingsAttribute(4194304);
  public static final SettingsAttribute PRIVACY_PROFILE_IMAGE_POST_TO_MYHOME = new SettingsAttribute(8388608);
  public static final SettingsAttribute EMAIL_CONFIRMATION_STATUS = new SettingsAttribute(16777216);
  public static final SettingsAttribute PRIVACY_RECV_MESSAGES_FROM_NOT_FRIEND = new SettingsAttribute(33554432);
  public static final SettingsAttribute ALL = new SettingsAttribute(2147483647);

  private final int value;

  private SettingsAttribute(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static SettingsAttribute findByValue(int value) { 
    switch (value) {
      case 1:
        return NOTIFICATION_ENABLE;
      case 2:
        return NOTIFICATION_MUTE_EXPIRATION;
      case 4:
        return NOTIFICATION_NEW_MESSAGE;
      case 8:
        return NOTIFICATION_GROUP_INVITATION;
      case 16:
        return NOTIFICATION_SHOW_MESSAGE;
      case 32:
        return NOTIFICATION_INCOMING_CALL;
      case 64:
        return PRIVACY_SYNC_CONTACTS;
      case 128:
        return PRIVACY_SEARCH_BY_PHONE_NUMBER;
      case 256:
        return NOTIFICATION_SOUND_MESSAGE;
      case 512:
        return NOTIFICATION_SOUND_GROUP;
      case 1024:
        return CONTACT_MY_TICKET;
      case 2048:
        return IDENTITY_PROVIDER;
      case 4096:
        return IDENTITY_IDENTIFIER;
      case 8192:
        return PRIVACY_SEARCH_BY_USERID;
      case 16384:
        return PRIVACY_SEARCH_BY_EMAIL;
      case 32768:
        return PREFERENCE_LOCALE;
      case 65536:
        return NOTIFICATION_DISABLED_WITH_SUB;
      case 524288:
        return SNS_ACCOUNT;
      case 1048576:
        return PHONE_REGISTRATION;
      case 2097152:
        return PRIVACY_ALLOW_SECONDARY_DEVICE_LOGIN;
      case 4194304:
        return CUSTOM_MODE;
      case 8388608:
        return PRIVACY_PROFILE_IMAGE_POST_TO_MYHOME;
      case 16777216:
        return EMAIL_CONFIRMATION_STATUS;
      case 33554432:
        return PRIVACY_RECV_MESSAGES_FROM_NOT_FRIEND;
      case 2147483647:
        return ALL;
      default:
        return null;
    }
  }
}
