// Autogenerated by Thrift Compiler (0.14.0)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	"github.com/apache/thrift/lib/go/thrift"
	"line"
)

var _ = line.GoUnusedProtection__

func Usage() {
  fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
  flag.PrintDefaults()
  fmt.Fprintln(os.Stderr, "\nFunctions:")
  fmt.Fprintln(os.Stderr, "  i64 activeBuddySubscriberCount()")
  fmt.Fprintln(os.Stderr, "  void addOperationForChannel(OpType opType, string param1, string param2, string param3)")
  fmt.Fprintln(os.Stderr, "  i64 displayBuddySubscriberCount()")
  fmt.Fprintln(os.Stderr, "  Contact findContactByUseridWithoutAbuseBlockForChannel(string userid)")
  fmt.Fprintln(os.Stderr, "   getAllContactIdsForChannel()")
  fmt.Fprintln(os.Stderr, "   getCompactContacts(i64 lastModifiedTimestamp)")
  fmt.Fprintln(os.Stderr, "   getContactsForChannel( ids)")
  fmt.Fprintln(os.Stderr, "  string getDisplayName(string mid)")
  fmt.Fprintln(os.Stderr, "   getFavoriteMidsForChannel()")
  fmt.Fprintln(os.Stderr, "   getFriendMids()")
  fmt.Fprintln(os.Stderr, "   getGroupMemberMids(string groupId)")
  fmt.Fprintln(os.Stderr, "   getGroupsForChannel( groupIds)")
  fmt.Fprintln(os.Stderr, "  IdentityCredential getIdentityCredential()")
  fmt.Fprintln(os.Stderr, "   getJoinedGroupIdsForChannel()")
  fmt.Fprintln(os.Stderr, "  MetaProfile getMetaProfile()")
  fmt.Fprintln(os.Stderr, "  string getMid()")
  fmt.Fprintln(os.Stderr, "  SimpleChannelClient getPrimaryClientForChannel()")
  fmt.Fprintln(os.Stderr, "  Profile getProfileForChannel()")
  fmt.Fprintln(os.Stderr, "   getSimpleChannelContacts( ids)")
  fmt.Fprintln(os.Stderr, "  string getUserCountryForBilling(string country, string remoteIp)")
  fmt.Fprintln(os.Stderr, "  i64 getUserCreateTime()")
  fmt.Fprintln(os.Stderr, "   getUserIdentities()")
  fmt.Fprintln(os.Stderr, "  string getUserLanguage()")
  fmt.Fprintln(os.Stderr, "   getUserMidsWhoAddedMe()")
  fmt.Fprintln(os.Stderr, "  bool isGroupMember(string groupId)")
  fmt.Fprintln(os.Stderr, "  bool isInContact(string mid)")
  fmt.Fprintln(os.Stderr, "  string registerChannelCP(string cpId, string registerPassword)")
  fmt.Fprintln(os.Stderr, "  void removeNotificationStatus(NotificationStatus notificationStatus)")
  fmt.Fprintln(os.Stderr, "  Message sendMessageForChannel(Message message)")
  fmt.Fprintln(os.Stderr, "  void sendPinCodeOperation(string verifier)")
  fmt.Fprintln(os.Stderr, "  void updateProfileAttributeForChannel(ProfileAttribute profileAttribute, string value)")
  fmt.Fprintln(os.Stderr)
  os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
  var m map[string]string = h
  return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
  parts := strings.Split(value, ": ")
  if len(parts) != 2 {
    return fmt.Errorf("header should be of format 'Key: Value'")
  }
  h[parts[0]] = parts[1]
  return nil
}

func main() {
  flag.Usage = Usage
  var host string
  var port int
  var protocol string
  var urlString string
  var framed bool
  var useHttp bool
  headers := make(httpHeaders)
  var parsedUrl *url.URL
  var trans thrift.TTransport
  _ = strconv.Atoi
  _ = math.Abs
  flag.Usage = Usage
  flag.StringVar(&host, "h", "localhost", "Specify host and port")
  flag.IntVar(&port, "p", 9090, "Specify port")
  flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
  flag.StringVar(&urlString, "u", "", "Specify the url")
  flag.BoolVar(&framed, "framed", false, "Use framed transport")
  flag.BoolVar(&useHttp, "http", false, "Use http")
  flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
  flag.Parse()
  
  if len(urlString) > 0 {
    var err error
    parsedUrl, err = url.Parse(urlString)
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
    host = parsedUrl.Host
    useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
  } else if useHttp {
    _, err := url.Parse(fmt.Sprint("http://", host, ":", port))
    if err != nil {
      fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
      flag.Usage()
    }
  }
  
  cmd := flag.Arg(0)
  var err error
  if useHttp {
    trans, err = thrift.NewTHttpClient(parsedUrl.String())
    if len(headers) > 0 {
      httptrans := trans.(*thrift.THttpClient)
      for key, value := range headers {
        httptrans.SetHeader(key, value)
      }
    }
  } else {
    portStr := fmt.Sprint(port)
    if strings.Contains(host, ":") {
           host, portStr, err = net.SplitHostPort(host)
           if err != nil {
                   fmt.Fprintln(os.Stderr, "error with host:", err)
                   os.Exit(1)
           }
    }
    trans, err = thrift.NewTSocket(net.JoinHostPort(host, portStr))
    if err != nil {
      fmt.Fprintln(os.Stderr, "error resolving address:", err)
      os.Exit(1)
    }
    if framed {
      trans = thrift.NewTFramedTransport(trans)
    }
  }
  if err != nil {
    fmt.Fprintln(os.Stderr, "Error creating transport", err)
    os.Exit(1)
  }
  defer trans.Close()
  var protocolFactory thrift.TProtocolFactory
  switch protocol {
  case "compact":
    protocolFactory = thrift.NewTCompactProtocolFactory()
    break
  case "simplejson":
    protocolFactory = thrift.NewTSimpleJSONProtocolFactory()
    break
  case "json":
    protocolFactory = thrift.NewTJSONProtocolFactory()
    break
  case "binary", "":
    protocolFactory = thrift.NewTBinaryProtocolFactoryDefault()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
    Usage()
    os.Exit(1)
  }
  iprot := protocolFactory.GetProtocol(trans)
  oprot := protocolFactory.GetProtocol(trans)
  client := line.NewChannelApplicationProvidedServiceClient(thrift.NewTStandardClient(iprot, oprot))
  if err := trans.Open(); err != nil {
    fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
    os.Exit(1)
  }
  
  switch cmd {
  case "activeBuddySubscriberCount":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "ActiveBuddySubscriberCount requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.ActiveBuddySubscriberCount(context.Background()))
    fmt.Print("\n")
    break
  case "addOperationForChannel":
    if flag.NArg() - 1 != 4 {
      fmt.Fprintln(os.Stderr, "AddOperationForChannel requires 4 args")
      flag.Usage()
    }
    tmp0, err := (strconv.Atoi(flag.Arg(1)))
    if err != nil {
      Usage()
     return
    }
    argvalue0 := line.OpType(tmp0)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    argvalue2 := flag.Arg(3)
    value2 := argvalue2
    argvalue3 := flag.Arg(4)
    value3 := argvalue3
    fmt.Print(client.AddOperationForChannel(context.Background(), value0, value1, value2, value3))
    fmt.Print("\n")
    break
  case "displayBuddySubscriberCount":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "DisplayBuddySubscriberCount requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.DisplayBuddySubscriberCount(context.Background()))
    fmt.Print("\n")
    break
  case "findContactByUseridWithoutAbuseBlockForChannel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "FindContactByUseridWithoutAbuseBlockForChannel requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.FindContactByUseridWithoutAbuseBlockForChannel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getAllContactIdsForChannel":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetAllContactIdsForChannel requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetAllContactIdsForChannel(context.Background()))
    fmt.Print("\n")
    break
  case "getCompactContacts":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetCompactContacts requires 1 args")
      flag.Usage()
    }
    argvalue0, err610 := (strconv.ParseInt(flag.Arg(1), 10, 64))
    if err610 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.GetCompactContacts(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getContactsForChannel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetContactsForChannel requires 1 args")
      flag.Usage()
    }
    arg611 := flag.Arg(1)
    mbTrans612 := thrift.NewTMemoryBufferLen(len(arg611))
    defer mbTrans612.Close()
    _, err613 := mbTrans612.WriteString(arg611)
    if err613 != nil { 
      Usage()
      return
    }
    factory614 := thrift.NewTJSONProtocolFactory()
    jsProt615 := factory614.GetProtocol(mbTrans612)
    containerStruct0 := line.NewChannelApplicationProvidedServiceGetContactsForChannelArgs()
    err616 := containerStruct0.ReadField1(jsProt615)
    if err616 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Ids
    value0 := argvalue0
    fmt.Print(client.GetContactsForChannel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getDisplayName":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetDisplayName requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetDisplayName(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getFavoriteMidsForChannel":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetFavoriteMidsForChannel requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetFavoriteMidsForChannel(context.Background()))
    fmt.Print("\n")
    break
  case "getFriendMids":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetFriendMids requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetFriendMids(context.Background()))
    fmt.Print("\n")
    break
  case "getGroupMemberMids":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetGroupMemberMids requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.GetGroupMemberMids(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getGroupsForChannel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetGroupsForChannel requires 1 args")
      flag.Usage()
    }
    arg619 := flag.Arg(1)
    mbTrans620 := thrift.NewTMemoryBufferLen(len(arg619))
    defer mbTrans620.Close()
    _, err621 := mbTrans620.WriteString(arg619)
    if err621 != nil { 
      Usage()
      return
    }
    factory622 := thrift.NewTJSONProtocolFactory()
    jsProt623 := factory622.GetProtocol(mbTrans620)
    containerStruct0 := line.NewChannelApplicationProvidedServiceGetGroupsForChannelArgs()
    err624 := containerStruct0.ReadField1(jsProt623)
    if err624 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.GroupIds
    value0 := argvalue0
    fmt.Print(client.GetGroupsForChannel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getIdentityCredential":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetIdentityCredential requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetIdentityCredential(context.Background()))
    fmt.Print("\n")
    break
  case "getJoinedGroupIdsForChannel":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetJoinedGroupIdsForChannel requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetJoinedGroupIdsForChannel(context.Background()))
    fmt.Print("\n")
    break
  case "getMetaProfile":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetMetaProfile requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetMetaProfile(context.Background()))
    fmt.Print("\n")
    break
  case "getMid":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetMid requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetMid(context.Background()))
    fmt.Print("\n")
    break
  case "getPrimaryClientForChannel":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetPrimaryClientForChannel requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetPrimaryClientForChannel(context.Background()))
    fmt.Print("\n")
    break
  case "getProfileForChannel":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetProfileForChannel requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetProfileForChannel(context.Background()))
    fmt.Print("\n")
    break
  case "getSimpleChannelContacts":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "GetSimpleChannelContacts requires 1 args")
      flag.Usage()
    }
    arg625 := flag.Arg(1)
    mbTrans626 := thrift.NewTMemoryBufferLen(len(arg625))
    defer mbTrans626.Close()
    _, err627 := mbTrans626.WriteString(arg625)
    if err627 != nil { 
      Usage()
      return
    }
    factory628 := thrift.NewTJSONProtocolFactory()
    jsProt629 := factory628.GetProtocol(mbTrans626)
    containerStruct0 := line.NewChannelApplicationProvidedServiceGetSimpleChannelContactsArgs()
    err630 := containerStruct0.ReadField1(jsProt629)
    if err630 != nil {
      Usage()
      return
    }
    argvalue0 := containerStruct0.Ids
    value0 := argvalue0
    fmt.Print(client.GetSimpleChannelContacts(context.Background(), value0))
    fmt.Print("\n")
    break
  case "getUserCountryForBilling":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "GetUserCountryForBilling requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.GetUserCountryForBilling(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "getUserCreateTime":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetUserCreateTime requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetUserCreateTime(context.Background()))
    fmt.Print("\n")
    break
  case "getUserIdentities":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetUserIdentities requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetUserIdentities(context.Background()))
    fmt.Print("\n")
    break
  case "getUserLanguage":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetUserLanguage requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetUserLanguage(context.Background()))
    fmt.Print("\n")
    break
  case "getUserMidsWhoAddedMe":
    if flag.NArg() - 1 != 0 {
      fmt.Fprintln(os.Stderr, "GetUserMidsWhoAddedMe requires 0 args")
      flag.Usage()
    }
    fmt.Print(client.GetUserMidsWhoAddedMe(context.Background()))
    fmt.Print("\n")
    break
  case "isGroupMember":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IsGroupMember requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IsGroupMember(context.Background(), value0))
    fmt.Print("\n")
    break
  case "isInContact":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "IsInContact requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.IsInContact(context.Background(), value0))
    fmt.Print("\n")
    break
  case "registerChannelCP":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "RegisterChannelCP requires 2 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.RegisterChannelCP(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "removeNotificationStatus":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "RemoveNotificationStatus requires 1 args")
      flag.Usage()
    }
    tmp0, err := (strconv.Atoi(flag.Arg(1)))
    if err != nil {
      Usage()
     return
    }
    argvalue0 := line.NotificationStatus(tmp0)
    value0 := argvalue0
    fmt.Print(client.RemoveNotificationStatus(context.Background(), value0))
    fmt.Print("\n")
    break
  case "sendMessageForChannel":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SendMessageForChannel requires 1 args")
      flag.Usage()
    }
    arg637 := flag.Arg(1)
    mbTrans638 := thrift.NewTMemoryBufferLen(len(arg637))
    defer mbTrans638.Close()
    _, err639 := mbTrans638.WriteString(arg637)
    if err639 != nil {
      Usage()
      return
    }
    factory640 := thrift.NewTJSONProtocolFactory()
    jsProt641 := factory640.GetProtocol(mbTrans638)
    argvalue0 := line.NewMessage()
    err642 := argvalue0.Read(jsProt641)
    if err642 != nil {
      Usage()
      return
    }
    value0 := argvalue0
    fmt.Print(client.SendMessageForChannel(context.Background(), value0))
    fmt.Print("\n")
    break
  case "sendPinCodeOperation":
    if flag.NArg() - 1 != 1 {
      fmt.Fprintln(os.Stderr, "SendPinCodeOperation requires 1 args")
      flag.Usage()
    }
    argvalue0 := flag.Arg(1)
    value0 := argvalue0
    fmt.Print(client.SendPinCodeOperation(context.Background(), value0))
    fmt.Print("\n")
    break
  case "updateProfileAttributeForChannel":
    if flag.NArg() - 1 != 2 {
      fmt.Fprintln(os.Stderr, "UpdateProfileAttributeForChannel requires 2 args")
      flag.Usage()
    }
    tmp0, err := (strconv.Atoi(flag.Arg(1)))
    if err != nil {
      Usage()
     return
    }
    argvalue0 := line.ProfileAttribute(tmp0)
    value0 := argvalue0
    argvalue1 := flag.Arg(2)
    value1 := argvalue1
    fmt.Print(client.UpdateProfileAttributeForChannel(context.Background(), value0, value1))
    fmt.Print("\n")
    break
  case "":
    Usage()
    break
  default:
    fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
  }
}
