/**
 * Compiled for SuperSonic Line API Lite
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ApplicationType
{
  DESKTOPWIN = 96,
  DESKTOPWIN_RC = 97,
  DESKTOPWIN_BETA = 98,
  DESKTOPWIN_ALPHA = 99,
  DESKTOPMAC = 112,
  DESKTOPMAC_RC = 113,
  DESKTOPMAC_BETA = 114,
  DESKTOPMAC_ALPHA = 115,
}
